export const FETCH_WISHPRODUCT = "FETCH_WISHPRODUCT";
export const ADD_WISHPRODUCT = "ADD_WISHPRODUCT";
export const EDIT_WISHPRODUCT = " EDIT_WISHPRODUCT";
export const DELETE_WISHPRODUCT = "DELETE_WISHPRODUCT";